services:
  kometa:
    image: kometateam/kometa
    container_name: kometa
    env_file:
      - .env
    command: --run
    volumes:
      - /opt/stacks/kometa/config:/config
    environment:
      - TZ=America/Phoenix
      - PLEX_URL=${PLEX_URL}
      - PLEX_API_TOKEN=${PLEX_TOKEN}
      - TMDB_API_TOKEN=${TMDB_API_TOKEN}
      - TAUTULLI_URL=${TAUTULLI_URL}
      - TAUTULLI_API_KEY=${TAUTULLI_API_KEY}
      - RADARR_URL=${RADARR_URL}
      - RADARR_API_KEY=${RADARR_API_KEY}
      - SONARR_URL=${SONARR_URL}
      - SONARR_API_KEY-${SONARR_API_KEY}
      - LIDARR_URL=${LIDARR_URL}
      - LIDARR_API_KEY=${LIDARR_API_KEY}
      - NOTIFIARR_API_KEY=${NOTIFIARR_API_KEY}
      - MDBLIST_API_KEY=${MDBLIST_API_KEY}
      - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}

networks: {}
